### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by olalonde** [semantic-release/condition-run-script#1]
It seems this module has no version and is not published to npm.

**Comment by ghost** [comment]
@olalonde it appears this module doesn't actually do anything (other than call `cb(null)`.

Does it need to be filled out first, or has the use for it been negated (and can it be deleted in that case)?

**Comment by pvdlg** [comment]
More comprehensive solution other there: https://github.com/semantic-release/exec

Will be published soon
